// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdnfpoytpesnuzcfpajd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbmZwb3l0cGVzbnV6Y2ZwYWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTQwNTQsImV4cCI6MjA1NjMzMDA1NH0.LglyloPlZQWebR2Yo3vfEZGdjS4auAaWn3wfh0VUeqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);